# Generated by Django 5.2.3 on 2025-07-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bean_app', '0003_prediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', max_length=255, upload_to='avatars/'),
        ),
    ]
